### ISSUE TITLE
Need a setting for admins to turn off new user registration

### ISSUE THREAD

**Issue by JasonSHD** [SquareHook/2Mean#126]
This may actually be 2 settings.  One for disabling new visitors from registering at all and one for just stopping the newly registered users from getting full user access.  The later I would think would allow admins to promote new applicants to full user status on some view.

**Comment by dylan-wright** [comment]
I can work on this after getting endpoint permissions ui implemented

**Comment by dylan-wright** [comment]
Created issue [SDK-442](https://squarehook.atlassian.net/browse/SDK-442)

**Comment by dylan-wright** [comment]
opened #129
