### ISSUE TITLE
Verification should occur whether you're logged in or not

### ISSUE THREAD

**Issue by JasonSHD** [SquareHook/2Mean#148]
It's a prohibitive UX feature that you have to be logged in for the verification token link to work.  It's not apparent what you need to do to have it verify you after you get the failed verification message at that point.  The better user experience would be to verify the user even if they're coming to the page cold.  Those tokens are so unique and (to my knowledge) limited in usage that it shouldn't be a security issue verifying them.

**Comment by dylan-wright** [comment]
Ok, this is an easy change
